//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloWebSovellus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JuhaDBEntities1 : DbContext
    {
        public JuhaDBEntities1()
            : base("name=JuhaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TalonLammot> TalonLammot { get; set; }
        public virtual DbSet<TalonSaunat> TalonSaunat { get; set; }
        public virtual DbSet<TalonValot> TalonValot { get; set; }
    }
}
