//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloWebSovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalonSaunat
    {
        public int SaunaId { get; set; }
        public int SaunaTavoiteLampoTila { get; set; }
        public int SaunaNykyLampoTila { get; set; }
        public string SaunanNimi { get; set; }
        public Nullable<System.DateTime> PaivaMaara { get; set; }
        public string SaunanTila { get; set; }
    }
}
