//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloWebSovellus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlytaloEntities : DbContext
    {
        public AlytaloEntities()
            : base("name=AlytaloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TalonLammot> TalonLammots { get; set; }
        public virtual DbSet<TalonSaunat> TalonSaunats { get; set; }
        public virtual DbSet<TalonValot> TalonValots { get; set; }
    }
}
