//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloWebSovellus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalonSaunat
    {
        public int SaunaId { get; set; }
        public string SaunaTavoiteLampotila { get; set; }
        public string SaunaNykyLampotila { get; set; }
        public int SaunanTila { get; set; }
        public string SaunanNimi { get; set; }
        public System.DateTime PaivaMaara { get; set; }
    }
}
