//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlytaloWebSovellus
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalonLammot
    {
        public int HuoneId { get; set; }
        public string Huone { get; set; }
        public string TavoiteLampotila { get; set; }
        public string TalonNykyLampotila { get; set; }
        public System.DateTime PaivaMaara { get; set; }
    }
}
